language: cpp

compiler:
# gcc test is disabled (see #120)
#  - gcc
  - clang

before_install:
  - lsb_release -a
  - uname -a
  - sudo apt-get -qq update

install:
  # msgpack
  - sudo apt-get -qq install libmsgpack-dev
  # oniguruma
  - wget https://github.com/kkos/oniguruma/releases/download/v5.9.6/onig-5.9.6.tar.gz && tar xvf onig-5.9.6.tar.gz
  - pushd onig-5.9.6 && ./configure && make && sudo make install && popd
  - sudo ldconfig

script:
  - ./waf configure
  - ./waf build --checkall

branches:
  only:
    - master
    - develop

notifications:
  email: false
